# Documentation: https://docs.gitlab.com/ee/topics/autodevops/customize.html

include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
  - template: Auto-DevOps.gitlab-ci.yml

default:
  tags:
    - linux
    - docker

variables:
  TEST_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  CONTAINER_SCANNING_DISABLED: "true"
  SECRET_DETECTION_DISABLED: "true"
  SAST_DISABLED: "true"
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375

ecr-registry-password:
  stage: .pre
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
  script:
    - echo "CI_REGISTRY_PASSWORD=$(aws ecr get-login-password --region eu-west-1)" > vars.env
  artifacts:
    reports:
      dotenv: vars.env

build:
  variables:
    CI_REGISTRY: "908648697511.dkr.ecr.eu-west-1.amazonaws.com"
    CI_REGISTRY_USER: "AWS"
    CI_APPLICATION_REPOSITORY: "908648697511.dkr.ecr.eu-west-1.amazonaws.com/podbeam-production-ecr"
    CI_APPLICATION_TAG: "auth-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"

.deploy_to_ecs:
  extends: .ecs_image
  dependencies: []
  variables:
    CI_REGISTRY: "908648697511.dkr.ecr.eu-west-1.amazonaws.com"
    CI_REGISTRY_USER: "AWS"
    CI_APPLICATION_REPOSITORY: "908648697511.dkr.ecr.eu-west-1.amazonaws.com/podbeam-production-ecr"
    CI_APPLICATION_TAG: "auth-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
  script:
    - ecs update-task-definition
