version: '3.8'

services:
  api:
    image: python:3.8.11-bullseye
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while ! nc -z db 27017; do sleep 1; done; while sleep 1000; do :; done"
    ports:
      - 8000:8000
    env_file:
      - services/api/api.env
    depends_on:
      - db
  auth:
    image: python:3.8.11-bullseye
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while ! nc -z db 27017; do sleep 1; done; while sleep 1000; do :; done"
    ports:
      - 8001:8000
    env_file:
      - services/auth/auth.env
    depends_on:
      - db
  mailing:
    image: python:3.8.11-bullseye
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while ! nc -z db 27017; do sleep 1; done; while sleep 1000; do :; done"
    ports:
      - 8002:8000
    env_file:
      - services/mailing/mailing.env
    depends_on:
      - db
  meeting:
    image: python:3.8.11-bullseye
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while ! nc -z db 27017; do sleep 1; done; while sleep 1000; do :; done"
    ports:
      - 8003:8000
    env_file:
      - services/mailing/mailing.env
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongodb_data:
