variables:
  S3_BUCKET: s3://www.podbeam.io
  CLOUDFRONT_DISTRO_ID: E1MFCKYQENSHK8

image: node:16.14.2-slim

stages:
  - build
  - push

build_spa:
  stage: build
  script:
    - echo "Building the static files"
    - npm install -g @vue/cli-service-global
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

static_push:
  image: python:latest
  stage: push
  script:
    - echo "Pushing the static files"
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - pip install awscli
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - aws s3 sync dist/ ${S3_BUCKET}/studio --acl public-read
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRO_ID} --paths /studio/*
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
